# Generated by Django 5.1.7 on 2025-03-10 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="zania_orders",
        ),
        migrations.AlterModelTable(
            name="product",
            table="zania_products",
        ),
    ]
